"""Write-or-check handling for generators whose output is committed."""

from __future__ import annotations

from pathlib import Path


class GeneratedOutputError(RuntimeError):
    """Reports committed output that is missing or differs from its regeneration."""


def write_or_check_output(path: Path, content: bytes, *, check: bool) -> None:
    """Writes regenerated bytes, or with check fails unless the committed file is identical."""

    if check:
        if not path.is_file():
            raise GeneratedOutputError(f"Committed output is missing: {path}")
        if path.read_bytes() != content:
            raise GeneratedOutputError(
                f"Regenerated output differs from the committed bytes: {path}"
            )
        return
    path.parent.mkdir(parents=True, exist_ok=True)
    # Replacing the file with a complete sibling never leaves truncated output behind
    temporary_path = path.with_name(f"{path.name}.tmp")
    temporary_path.write_bytes(content)
    temporary_path.replace(path)
