#!/usr/bin/env python3
"""Generate bounded DTS capability access units from public-domain fixtures."""

from __future__ import annotations

import argparse
import base64
import json
from pathlib import Path
from typing import Final

from generated_output import write_or_check_output


REPOSITORY_ROOT: Final = Path(__file__).resolve().parents[1]
# The generated fixture list keeps this order
FIXTURE_FILE_NAMES: Final = (
    "core_51_24_48_768_0.dtshd",
    "x96_51_24_96_1509.dtshd",
    "xch_61_24_48_768.dtshd",
    "xbr_xxch_71_24_48_3840.dtshd",
    "xll_71_24_48_768_0.dtshd",
    "xll_71_24_96_768.dtshd",
    "xll_51_16_192_768_0.dtshd",
)


def parse_arguments() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--fixture-directory",
        type=Path,
        default=REPOSITORY_ROOT / "fixtures/test/dts",
    )
    parser.add_argument(
        "--output",
        type=Path,
        default=REPOSITORY_ROOT / "src/custom/DTSExactCapabilityFixtures.ts",
    )
    parser.add_argument(
        "--check",
        action="store_true",
        help="Fail if the committed output differs from the regenerated output",
    )
    return parser.parse_args()


def generate_typescript(fixture_directory: Path) -> str:
    packet_definitions = json.loads(
        (fixture_directory / "packets.json").read_text(encoding="utf-8")
    )
    generated_definitions: list[str] = []
    for file_name in FIXTURE_FILE_NAMES:
        fixture_data = (fixture_directory / file_name).read_bytes()
        definition = packet_definitions[file_name]
        packet_index = int(definition["qualificationPacketIndex"])
        stereo_fingerprint = definition.get("qualificationStereoFingerprint")
        stereo_fingerprint_typescript = (
            str(int(stereo_fingerprint))
            if stereo_fingerprint is not None
            else "null"
        )
        encoded_access_units: list[str] = []
        for packet_offset, packet_length in definition["packets"][: packet_index + 1]:
            access_unit = fixture_data[packet_offset : packet_offset + packet_length]
            if len(access_unit) != packet_length:
                raise RuntimeError(f"DTS qualification packet is truncated: {file_name}")
            encoded_access_units.append(
                base64.b64encode(access_unit).decode("ascii")
            )
        access_units_typescript = ", ".join(
            f"'{encoded_access_unit}'"
            for encoded_access_unit in encoded_access_units
        )
        generated_definitions.append(
            "    Object.freeze({\n"
            f"        accessUnitsBase64: Object.freeze([{access_units_typescript}]),\n"
            f"        bitsPerSample: {int(definition['expectedBitsPerSample'])},\n"
            f"        channelMask: {int(definition['expectedChannelMask'])},\n"
            f"        expectedFingerprint: {int(definition['qualificationFingerprint'])},\n"
            f"        expectedStereoFingerprint: {stereo_fingerprint_typescript},\n"
            f"        frameCount: {int(definition['qualificationFrameCount'])},\n"
            f"        profile: {int(definition['expectedProfile'])},\n"
            f"        sampleRate: {int(definition['expectedSampleRate'])},\n"
            f"        source: '{file_name}'\n"
            "    })"
        )

    definitions = ",\n".join(generated_definitions)
    return f"""// Generated by tools/generate_dts_capability_fixtures.py
// Source samples are public domain; see fixtures/test/dts/PROVENANCE.txt

import type {{ DTSDecodedProfile }} from './DTSSoftwareAudioDecoder';

export type DTSExactCapabilityFixture = Readonly<{{
    accessUnits: readonly Uint8Array[]
    bitsPerSample: 16 | 24
    channelMask: number
    expectedFingerprint: number
    expectedStereoFingerprint: number | null
    frameCount: number
    profile: DTSDecodedProfile
    sampleRate: 48_000 | 96_000 | 192_000
    source: string
}}>;

type EncodedDTSExactCapabilityFixture = Omit<
    DTSExactCapabilityFixture,
    'accessUnits'
> & Readonly<{{ accessUnitsBase64: readonly string[] }}>;

const ENCODED_DTS_EXACT_CAPABILITY_FIXTURES = Object.freeze([
{definitions}
]) satisfies readonly EncodedDTSExactCapabilityFixture[];

function decodeBase64(value: string): Uint8Array {{
    const decoded = globalThis.atob(value);
    const bytes = new Uint8Array(decoded.length);
    for (let byteIndex = 0; byteIndex < decoded.length; byteIndex += 1) {{
        bytes[byteIndex] = decoded.charCodeAt(byteIndex);
    }}
    return bytes;
}}

/** Creates isolated qualification access units for every authorized DTS profile. */
export function createDTSExactCapabilityFixtures(): readonly DTSExactCapabilityFixture[] {{
    const fixtures: DTSExactCapabilityFixture[] = [];
    for (const fixture of ENCODED_DTS_EXACT_CAPABILITY_FIXTURES) {{
        fixtures.push(Object.freeze({{
            accessUnits: Object.freeze(fixture.accessUnitsBase64.map(decodeBase64)),
            bitsPerSample: fixture.bitsPerSample,
            channelMask: fixture.channelMask,
            expectedFingerprint: fixture.expectedFingerprint,
            expectedStereoFingerprint: fixture.expectedStereoFingerprint,
            frameCount: fixture.frameCount,
            profile: fixture.profile,
            sampleRate: fixture.sampleRate,
            source: fixture.source
        }}));
    }}
    return Object.freeze(fixtures);
}}
"""


def main() -> None:
    arguments = parse_arguments()
    output_path = arguments.output.resolve()
    generated_typescript = generate_typescript(arguments.fixture_directory.resolve())
    write_or_check_output(
        output_path,
        generated_typescript.encode("utf-8"),
        check=arguments.check,
    )
    action = "Verified" if arguments.check else "Generated"
    print(f"{action} {output_path}")


if __name__ == "__main__":
    main()
